/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/_authenticated/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/_authenticated/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/_authenticated/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/_authenticated/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/_authenticated/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/_authenticated/integrations',
    path: '/integrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/_authenticated/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/_authenticated/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/_authenticated/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/ai': typeof AuthenticatedAiRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/production': typeof AuthenticatedProductionRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/ai': typeof AuthenticatedAiRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/production': typeof AuthenticatedProductionRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ai'
    | '/crm'
    | '/finance'
    | '/integrations'
    | '/inventory'
    | '/marketing'
    | '/production'
    | '/sales'
    | '/team'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai'
    | '/crm'
    | '/finance'
    | '/integrations'
    | '/inventory'
    | '/marketing'
    | '/production'
    | '/sales'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/ai'
    | '/_authenticated/crm'
    | '/_authenticated/finance'
    | '/_authenticated/integrations'
    | '/_authenticated/inventory'
    | '/_authenticated/marketing'
    | '/_authenticated/production'
    | '/_authenticated/sales'
    | '/_authenticated/team'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
